Repository firstof9/ha-renogy, pull requests merged in 2024-12, with the labels that each got.

#4 fix: library bump
  .github/workflows/release.yaml
  custom_components/renogy/manifest.json
Labels: bugfix

#5 feat: add diagnostics
  custom_components/renogy/diagnostics.py
  tests/const.py
  tests/test_config_flow.py
  tests/test_diagnostics.py
Labels: feature

#6 fix: change device class for 'heating mode'
  custom_components/renogy/const.py
Labels: bugfix

#7 fix: fix unit of measurement for `totalkwhgenerated`
  custom_components/renogy/const.py
Labels: bugfix

#8 fix: fix potential duplicate `binary_sensors`
  custom_components/renogy/__init__.py
  custom_components/renogy/binary_sensor.py
  custom_components/renogy/const.py
  tests/conftest.py
  tests/const.py
  tests/fixtures/realtime_data_2.json
  tests/test_binary_sensor.py
  tests/test_init.py
  tests/test_sensor.py
Labels: bugfix

#9 fix: more unit of measurement fixes
  custom_components/renogy/const.py
Labels: bugfix

#13 fix: fix devices not properly nesting
  custom_components/renogy/__init__.py
Labels: bugfix

#15 fix: fix entity connections to devices
  custom_components/renogy/binary_sensor.py
  custom_components/renogy/sensor.py
Labels: bugfix

#18 fix: fix errors with new sensors
  custom_components/renogy/const.py
  custom_components/renogy/sensor.py
  tests/test_binary_sensor.py
  tests/test_init.py
  tests/test_sensor.py
Labels: bugfix

#24 chore: update README.md
  README.md
Labels: documentation

#27 fix: handle API calls that return no devices
  custom_components/renogy/config_flow.py
  custom_components/renogy/manifest.json
  custom_components/renogy/strings.json
  custom_components/renogy/translations/en.json
  requirements.txt
  tests/conftest.py
  tests/test_config_flow.py
Labels: bugfix
