Repository firstof9/ha-renogy, pull requests merged in 2025-01, with the labels that each got.

#36 fix: add more sensors
  custom_components/renogy/const.py
Labels: bugfix

#37 fix: add `current` sensor
  custom_components/renogy/const.py
Labels: bugfix

#38 fix: adjust door/window contact sensor name
  custom_components/renogy/const.py
Labels: bugfix

#39 fix: attempt to handle duplicate serial numbers on devices
  custom_components/renogy/__init__.py
  custom_components/renogy/const.py
Labels: bugfix

#41 fix: more dupe serial number fixes
  custom_components/renogy/__init__.py
  custom_components/renogy/binary_sensor.py
  custom_components/renogy/sensor.py
  tests/conftest.py
  tests/const.py
  tests/test_init.py
Labels: bugfix

#43 chore(docs): update README.md
  README.md
Labels: chore

#44 chore: update `py_renogy` to 1.0.5
  custom_components/renogy/manifest.json
  requirements.txt
Labels: dependencies, chore

#45 chore(docs): update README.md
  README.md
Labels: documentation

#46 fix: parse batteryType and return string value if value is number
  custom_components/renogy/sensor.py
  tests/conftest.py
  tests/const.py
  tests/test_init.py
  tests/test_sensor.py
  tox.ini
Labels: bugfix

#47 fix: move `heatingModeStatus` out of `diagnostic` category
  custom_components/renogy/const.py
Labels: bugfix

#50 Update README.md
  README.md
Labels: documentation

#52 fix: fix `output` enum not enum'ing
  custom_components/renogy/sensor.py
  tests/test_sensor.py
Labels: bugfix
